name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-levels: 31
        target: android-31
        ndk: 21.4.7075529

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name
